version: '3'
services:
  data_science:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: issaiass/data_science:v1
    user: root # data_science
    volumes:
      - ../:/app
    ports:
      - 8888:8888
    working_dir: /app
    command: >
      /bin/sh -c "
      echo \"c.NotebookApp.password = ''\" >> ~/.jupyter/jupyter_notebook_config.py && \
      echo \"c.NotebookApp.token = ''\" >> ~/.jupyter/jupyter_notebook_config.py && \
      jupyter notebook --notebook-dir=/app --ip=0.0.0.0 --port=8888 --allow-root --no-browser"